### ISSUE TITLE
Pacman issues on Arch Linux

### ISSUE THREAD

**Issue by CrazySpike** [gsanhueza/ArchISOMaker#19]
I've been experiencing issues running sudo ./build -v on Arch Linux (minimal) through virtual machines like VirtualBox and UTM, where Pacman doesn't have the write permissions for the TEMPMNT directory. I've tried changing the permissions to allow all users rwx privileges, but to no avail. It works just fine in WSL but not on the base Arch Linux. The issue is from this line of code in utilities/custom_tools.sh:

pacman -Syw **--root ${TEMP_MNT}** --cachedir ${PKG_CACHE_DIR} --noconfirm $ALL_PACKAGES

<img width="1054" height="306" alt="Image" src="https://github.com/user-attachments/assets/6bc038b5-a6a4-4dc1-87a3-0703cce23cc1" />

Is there something I'm doing wrong?

**Comment by gsanhueza** [comment]
It's possible that you used it once before, and interrupted the process.
I've seen this happening when I interrupt the download of an update process.

Deleting TEMPMNT with `sudo rm -rf TEMPMNT` and re-trying should solve the issue.

**Comment by CrazySpike** [comment]
I've tried removing TEMPMNT, but got this error when running build.sh afterwards:
<img width="833" height="123" alt="Image" src="https://github.com/user-attachments/assets/334b424a-41a8-474a-8838-e8e3c16e1fc2" />
I've tried deleting the Git repository, then cloning it again, and getting the original error. Then I've removed TEMPNT and run it again, but I'm still getting this new error.

**Comment by gsanhueza** [comment]
Can you describe more about the environment that you're currently using?
For example, "I'm using windows, with the Git Bash console" or "I'm using Mingw", or "I'm using WSL".

> It works just fine in WSL but not on the base Arch Linux

What do you mean with "the base Arch Linux"? A minimal installation in a VM?
On the other hand, the photos of the console have a font that reminds me of the default Windows terminal.

With a detailed description of your environment, I can try to replicate your problems and check for possible errors in the configuration.

**Comment by CrazySpike** [comment]
Sure thing. I am using both UTM (emulating x86) on a MacBook M4 laptop and a Windows 11 laptop running VirtualBox; experiencing the same issues with both. For both versions I am using a minimal installation of Arch Linux with the only extra packages being git and archiso. The font is default in UTM which is what the screenshots are taken of. bwr is a sudoer using the wheel group and should have the correct permissions.

**Comment by gsanhueza** [comment]
I've replicated your error. I created a VirtualBox machine with the default ArchLinux installation.

The "Permission denied" part happened because the host machine (in your case, your minimal ArchLinux) has an uncommented `DownloadUser = alpm` in the host's `/etc/pacman.conf` file.

Although that was originally used for handling downloads in the host machine (recommend checking the Arch wiki to understand its original purpose), it seems to have some issues here, as you've reported it.
Try commenting that line, as the image shows, and let me know if it works.

<img width="1306" height="820" alt="Image" src="https://github.com/user-attachments/assets/6e582d22-03fe-46fe-91e3-51db3f3dd10b" />

**Comment by CrazySpike** [comment]
That has resolved my issue. Thank you very much.
